version: 2.0.0.{build}
os: Visual Studio 2017
environment:
  Major: 2
  Minor: 0
  Patch: 0
configuration: Release
services: mongodb
before_build:
- .\bootstrap.cmd
build:
  project: master.proj
  verbosity: minimal
test: off
artifacts:
- path: Build\*.nupkg
deploy:
- provider: Environment
  name: MyGet