version: 4.0.0.{build}
os: Visual Studio 2019
environment:
  ASPNETCORE_ENVIRONMENT: appveyor

init:
  - git config --global core.autocrlf input

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

services: mongodb

build_script:
  - dotnet pack MongoDB.Abstracts.sln --configuration Release --include-symbols --include-source

test_script:
  - dotnet test MongoDB.Abstracts.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"

artifacts:
- path: artifacts\*.*nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet