<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestResults\**" />
    <EmbeddedResource Remove="TestResults\**" />
    <None Remove="TestResults\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Injectio" PrivateAssets="all" />
    <PackageReference Include="XUnit.Hosting" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MongoDB.Abstracts\MongoDB.Abstracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Bogus" />
    <Using Include="AwesomeAssertions" />
    <Using Include="Injectio.Attributes" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="Xunit.CaptureConsoleAttribute" />
    <AssemblyAttribute Include="Xunit.CaptureTraceAttribute" />
  </ItemGroup>
</Project>
